Repository 2025-Summer-Bootcamp-Team-H/frontend, pull requests merged in 2025-07, with the labels that each got.

#3 Chore/#2: 초기 세팅 완료
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .gitignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: Chore

#5 chore: 기초 세팅
  public/vite.svg
  src/assets/fonts/sample.js
  src/assets/react.svg
  src/components/buttons/sample.js
  src/pages/sample.js
  src/styles/GlobalStyle.js
Labels: Chore

#11 Fix: eslint 오류 해결
  eslint.config.js
Labels: Fix

#18 Design: 로그인 페이지 퍼블리싱
  src/pages/Login.jsx
Labels: Design

#22 Design: 회원가입 페이지 퍼블리싱
  src/pages/Signup.jsx
Labels: Design

#25 Design: 위조분석 페이지 퍼블리싱
  src/pages/Analysis.jsx
Labels: Design

#31 Design: 관리 페이지 퍼블리싱
  src/pages/Management.jsx
Labels: Design

#32 feat: 완료페이지 구현
  src/pages/Complete.jsx
Labels: Design

#40 Design: 리포트 페이지 퍼블리싱
  src/pages/Report.jsx
Labels: Design

#41 Design: 메인 페이지 퍼블리싱
  src/assets/Navbar/logowhite.png
  src/pages/Onboarding.jsx
Labels: Design

#42 Design: 라우터 설정
  src/App.jsx
  src/pages/Analysis.jsx
  src/pages/Complete.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Login.jsx
  src/pages/Management.jsx
  src/pages/Onboarding.jsx
  src/pages/Receipt_edit.jsx
  src/pages/Report.jsx
  src/pages/Upload.jsx
Labels: Design

#46 Design: 온보딩 페이지 퍼블리싱 수정
  package-lock.json
  package.json
  src/assets/Onboarding/Customer.png
  src/assets/Onboarding/Management.png
  src/assets/Onboarding/OldMan.png
  src/assets/Onboarding/Report.png
  src/assets/Onboarding/Second.png
  src/assets/Onboarding/Third.png
  src/assets/Onboarding/User.png
  src/assets/Onboarding/YoungMan.png
  src/assets/Onboarding/YoungMan2.png
  src/assets/Onboarding/YoungWoman.png
  src/assets/Onboarding/logo.png
  src/pages/Onboarding.jsx
Labels: Design

#52 Feat: Management 페이지 API 연동
  package-lock.json
  package.json
  src/config/api.js
  src/hooks/useAPI.js
  src/pages/Management.jsx
  src/services/apiClient.js
  src/services/claimsAPI.js
  src/services/index.js
Labels: Feat

#55 Chore: 로그인페이지, 관리페이지 파일 통일
  src/components/Navbar.jsx
  src/config/api.js
  src/pages/Login.jsx
  src/pages/Report.jsx
  src/services/authAPI.js
  src/services/claimsAPI.js
  src/services/index.js
Labels: Chore

#57 Feat: Signup 페이지 API 연동
  src/pages/Signup.jsx
  src/services/authAPI.js
Labels: Feat

#59 Feat: 관리, 보고서 페이지 API 연동
  package-lock.json
  package.json
  src/pages/Management.jsx
  src/pages/Report.jsx
  src/services/claimsAPI.js
Labels: Feat

#61 Feat: Upload, Analysis 페이지 API 연동
  src/assets/Analysis/Check.png
  src/assets/Analysis/Reject.png
  src/pages/Analysis.jsx
  src/pages/Upload.jsx
  src/services/apiClient.js
  src/services/diagnosisAPI.js
  src/services/forgeryAPI.js
  src/services/index.js
  src/services/receiptAPI.js
Labels: Feat

#66 Design: 디자인 수정
  src/components/Navbar.jsx
  src/pages/Analysis.jsx
  src/pages/Complete.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Receipt_edit.jsx
  src/pages/Upload.jsx
Labels: Design

#67 Feat: api 연동 마무리
  src/components/Container.jsx
  src/components/LoadingOverlay.jsx
  src/components/buttons/Smallbtn.jsx
  src/hooks/useAPI.js
  src/pages/Analysis.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Receipt_edit.jsx
  src/pages/Report.jsx
  src/pages/Upload.jsx
  src/services/claimsAPI.js
  src/services/diagnosisAPI.js
  src/services/receiptAPI.js
Labels: Feat

#70 Design: 디자인 수정3
  src/pages/Analysis.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Management.jsx
  src/pages/Receipt_edit.jsx
Labels: Design

#79 Design: 디자인 수정4
  src/pages/Onboarding.jsx
Labels: Design

#82 design: 리포트 페이지 디자인 수정
  src/pages/Report.jsx
Labels: Design

#87 Design: progressbar 디자인 수정
  src/pages/Analysis.jsx
  src/pages/Complete.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Receipt_edit.jsx
  src/pages/Upload.jsx
Labels: Design

#89 Design: progress bar 오류 수정
  src/pages/Analysis.jsx
  src/pages/Complete.jsx
  src/pages/Diagnosis_edit.jsx
  src/pages/Receipt_edit.jsx
  src/pages/Upload.jsx
Labels: Design
